.PHONY: clean All

All:
	@echo "----------Building project:[ robotarm - Debug ]----------"
	@cd "robotarm" && "$(MAKE)" -f  "robotarm.mk" && "$(MAKE)" -f  "robotarm.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ robotarm - Debug ]----------"
	@cd "robotarm" && "$(MAKE)" -f  "robotarm.mk" clean
