.PHONY: clean All

All:
	@echo "----------Building project:[ forelasning_1 - Debug ]----------"
	@cd "forelasning_1" && "$(MAKE)" -f  "forelasning_1.mk"
clean:
	@echo "----------Cleaning project:[ forelasning_1 - Debug ]----------"
	@cd "forelasning_1" && "$(MAKE)" -f  "forelasning_1.mk" clean
