.PHONY: clean All

All:
	@echo "----------Building project:[ flipflop_irq_2 - Debug ]----------"
	@cd "flipflop_irq_2" && "$(MAKE)" -f  "flipflop_irq_2.mk" && "$(MAKE)" -f  "flipflop_irq_2.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ flipflop_irq_2 - Debug ]----------"
	@cd "flipflop_irq_2" && "$(MAKE)" -f  "flipflop_irq_2.mk" clean
